name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      
    # - name: Install Python dependencies
    #   run: |
    #     pip install -r requirements.txt  # Assuming your dependencies are listed in requirements.txt
      
    - name: Package Lambda function
      run: |
        zip -r function.zip . -x "*.git*"  # Package your Python code into a ZIP file, excluding git files
        aws lambda update-function-code --function-name TestFunction --zip-file fileb://function.zip
